[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "info"

[server]
headless = true
port = 8504
maxUploadSize = 200
